# -*- coding: utf-8 -*-
"""event.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S960Y5BP_g0_K_w9s1otUWAEPt_NEQKy
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the CSV file into a DataFrame, specifying the delimiter and handling bad lines
df = pd.read_csv('event_feedback.csv.csv', sep=',', on_bad_lines='skip')

print(df.head())
print(df.info())

df = df.drop_duplicates()

print(df.isnull().sum())

df['feedback'] = df['feedback'].str.strip().str.capitalize()

# Define a function to compute polarity and sentiment label
from textblob import TextBlob

def get_sentiment(text):
    blob = TextBlob(str(text))
    polarity = blob.sentiment.polarity
    if polarity > 0:
        return 'Positive'
    elif polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'

# Apply to the 'feedback' column
df['Sentiment'] = df['feedback'].apply(get_sentiment)
print(df[['feedback', 'Sentiment']].head())
print(df['Sentiment'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='Sentiment', data=df, palette='viridis')
plt.title('Sentiment Distribution')
plt.show()

print(df['rating'].describe())

import pandas as pd

# Load your CSV file with appropriate parameters to handle parsing issues
df = pd.read_csv('event_feedback.csv.csv', sep=',', on_bad_lines='skip')

# If you have multiple events, filter for a specific event
event_name = "Cultural Fest"
event_df = df[df['event'] == event_name]
event_df['feedback'] = event_df['feedback'].str.strip().str.capitalize()
event_df = event_df.dropna(subset=['feedback'])
print(event_df['rating'].describe())
print(event_df['rating'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='rating', data=event_df, palette='Blues')
plt.title('Rating Distribution for Cultural Fest')
plt.show()

# Recommendations
print("\nRecommendations:")
print("1. Improve event organization based on negative feedback.")
print("2.Continue with the current planning methods, as many attendees praised the event’s organization")
print("3.Address recurring sound quality complaints by investing in better audio equipment and conducting sound checks")